import type { Route as _IndexRoute } from '../pages/';
import type { Route as _AboutRoute } from '../pages/about';
/* eslint-disable */
// This file is auto-generated by @granite-js/react-native. DO NOT EDIT.
import type { Route as _ActiveWorkoutRoute } from '../pages/active-workout';
import type { Route as _AiAnalysisRoute } from '../pages/ai-analysis';
import type { Route as _AiHubRoute } from '../pages/ai-hub';
import type { Route as _AiTrainerMatchRoute } from '../pages/ai-trainer-match';
import type { Route as _AnalysisHistoryRoute } from '../pages/analysis-history';
import type { Route as _ConditionRoute } from '../pages/condition';
import type { Route as _ConditionFormRoute } from '../pages/condition-form';
import type { Route as _ConditionListRoute } from '../pages/condition-list';
import type { Route as _ExerciseRoute } from '../pages/exercise';
import type { Route as _ExerciseFormRoute } from '../pages/exercise-form';
import type { Route as _ExerciseGuideRoute } from '../pages/exercise-guide';
import type { Route as _ExerciseListRoute } from '../pages/exercise-list';
import type { Route as _ExerciseRecordDetailRoute } from '../pages/exercise-record-detail';
import type { Route as _ExerciseVideoViewerRoute } from '../pages/exercise-video-viewer';
import type { Route as _MealAnalysisRoute } from '../pages/meal-analysis';
import type { Route as _OutdoorWorkoutRoute } from '../pages/outdoor-workout';
import type { Route as _OutdoorWorkoutResultRoute } from '../pages/outdoor-workout-result';
import type { Route as _ProgressChartRoute } from '../pages/progress-chart';
import type { Route as _PtLessonFormRoute } from '../pages/pt-lesson-form';
import type { Route as _PtLogRoute } from '../pages/pt-log';

declare module '@granite-js/react-native' {
  interface RegisterScreenInput {
    '/active-workout': (typeof _ActiveWorkoutRoute)['_inputType'];
    '/ai-analysis': (typeof _AiAnalysisRoute)['_inputType'];
    '/ai-hub': (typeof _AiHubRoute)['_inputType'];
    '/ai-trainer-match': (typeof _AiTrainerMatchRoute)['_inputType'];
    '/analysis-history': (typeof _AnalysisHistoryRoute)['_inputType'];
    '/about': (typeof _AboutRoute)['_inputType'];
    '/condition': (typeof _ConditionRoute)['_inputType'];
    '/condition-form': (typeof _ConditionFormRoute)['_inputType'];
    '/condition-list': (typeof _ConditionListRoute)['_inputType'];
    '/exercise-guide': (typeof _ExerciseGuideRoute)['_inputType'];
    '/exercise': (typeof _ExerciseRoute)['_inputType'];
    '/exercise-form': (typeof _ExerciseFormRoute)['_inputType'];
    '/exercise-list': (typeof _ExerciseListRoute)['_inputType'];
    '/exercise-record-detail': (typeof _ExerciseRecordDetailRoute)['_inputType'];
    '/exercise-video-viewer': (typeof _ExerciseVideoViewerRoute)['_inputType'];
    '/meal-analysis': (typeof _MealAnalysisRoute)['_inputType'];
    '/outdoor-workout': (typeof _OutdoorWorkoutRoute)['_inputType'];
    '/outdoor-workout-result': (typeof _OutdoorWorkoutResultRoute)['_inputType'];
    '/pt-lesson-form': (typeof _PtLessonFormRoute)['_inputType'];
    '/pt-log': (typeof _PtLogRoute)['_inputType'];
    '/progress-chart': (typeof _ProgressChartRoute)['_inputType'];
    '/': (typeof _IndexRoute)['_inputType'];
  }

  interface RegisterScreen {
    '/active-workout': (typeof _ActiveWorkoutRoute)['_outputType'];
    '/ai-analysis': (typeof _AiAnalysisRoute)['_outputType'];
    '/ai-hub': (typeof _AiHubRoute)['_outputType'];
    '/ai-trainer-match': (typeof _AiTrainerMatchRoute)['_outputType'];
    '/analysis-history': (typeof _AnalysisHistoryRoute)['_outputType'];
    '/about': (typeof _AboutRoute)['_outputType'];
    '/condition': (typeof _ConditionRoute)['_outputType'];
    '/condition-form': (typeof _ConditionFormRoute)['_outputType'];
    '/condition-list': (typeof _ConditionListRoute)['_outputType'];
    '/exercise-guide': (typeof _ExerciseGuideRoute)['_outputType'];
    '/exercise': (typeof _ExerciseRoute)['_outputType'];
    '/exercise-form': (typeof _ExerciseFormRoute)['_outputType'];
    '/exercise-list': (typeof _ExerciseListRoute)['_outputType'];
    '/exercise-record-detail': (typeof _ExerciseRecordDetailRoute)['_outputType'];
    '/exercise-video-viewer': (typeof _ExerciseVideoViewerRoute)['_outputType'];
    '/meal-analysis': (typeof _MealAnalysisRoute)['_outputType'];
    '/outdoor-workout': (typeof _OutdoorWorkoutRoute)['_outputType'];
    '/outdoor-workout-result': (typeof _OutdoorWorkoutResultRoute)['_outputType'];
    '/pt-lesson-form': (typeof _PtLessonFormRoute)['_outputType'];
    '/pt-log': (typeof _PtLogRoute)['_outputType'];
    '/progress-chart': (typeof _ProgressChartRoute)['_outputType'];
    '/': (typeof _IndexRoute)['_outputType'];
  }
}
