import type { Route as _IndexRoute } from "../pages/";
import type { Route as _AboutRoute } from "../pages/about";
/* eslint-disable */
// This file is auto-generated by @granite-js/react-native. DO NOT EDIT.
import type { Route as _ActiveWorkoutRoute } from "../pages/active-workout";
import type { Route as _ConditionFormRoute } from "../pages/condition-form";
import type { Route as _ConditionListRoute } from "../pages/condition-list";
import type { Route as _ExerciseGuideRoute } from "../pages/exercise-guide";
import type { Route as _ExerciseRoute } from "../pages/exercise";
import type { Route as _ExerciseFormRoute } from "../pages/exercise-form";
import type { Route as _ExerciseListRoute } from "../pages/exercise-list";
import type { Route as _ExerciseRecordDetailRoute } from "../pages/exercise-record-detail";
import type { Route as _ExerciseVideoViewerRoute } from "../pages/exercise-video-viewer";
import type { Route as _OutdoorWorkoutRoute } from "../pages/outdoor-workout";
import type { Route as _OutdoorWorkoutResultRoute } from "../pages/outdoor-workout-result";
import type { Route as _ProgressChartRoute } from "../pages/progress-chart";

declare module "@granite-js/react-native" {
  interface RegisterScreenInput {
    "/active-workout": (typeof _ActiveWorkoutRoute)["_inputType"];
    "/about": (typeof _AboutRoute)["_inputType"];
    "/condition-form": (typeof _ConditionFormRoute)["_inputType"];
    "/condition-list": (typeof _ConditionListRoute)["_inputType"];
    "/exercise-guide": (typeof _ExerciseGuideRoute)["_inputType"];
    "/exercise": (typeof _ExerciseRoute)["_inputType"];
    "/exercise-form": (typeof _ExerciseFormRoute)["_inputType"];
    "/exercise-list": (typeof _ExerciseListRoute)["_inputType"];
    "/exercise-record-detail": (typeof _ExerciseRecordDetailRoute)["_inputType"];
    "/exercise-video-viewer": (typeof _ExerciseVideoViewerRoute)["_inputType"];
    "/outdoor-workout": (typeof _OutdoorWorkoutRoute)["_inputType"];
    "/outdoor-workout-result": (typeof _OutdoorWorkoutResultRoute)["_inputType"];
    "/progress-chart": (typeof _ProgressChartRoute)["_inputType"];
    "/": (typeof _IndexRoute)["_inputType"];
  }

  interface RegisterScreen {
    "/active-workout": (typeof _ActiveWorkoutRoute)["_outputType"];
    "/about": (typeof _AboutRoute)["_outputType"];
    "/condition-form": (typeof _ConditionFormRoute)["_outputType"];
    "/condition-list": (typeof _ConditionListRoute)["_outputType"];
    "/exercise-guide": (typeof _ExerciseGuideRoute)["_outputType"];
    "/exercise": (typeof _ExerciseRoute)["_outputType"];
    "/exercise-form": (typeof _ExerciseFormRoute)["_outputType"];
    "/exercise-list": (typeof _ExerciseListRoute)["_outputType"];
    "/exercise-record-detail": (typeof _ExerciseRecordDetailRoute)["_outputType"];
    "/exercise-video-viewer": (typeof _ExerciseVideoViewerRoute)["_outputType"];
    "/outdoor-workout": (typeof _OutdoorWorkoutRoute)["_outputType"];
    "/outdoor-workout-result": (typeof _OutdoorWorkoutResultRoute)["_outputType"];
    "/progress-chart": (typeof _ProgressChartRoute)["_outputType"];
    "/": (typeof _IndexRoute)["_outputType"];
  }
}
