map $http_x_forwarded_proto $forwarded_proto {
  default $http_x_forwarded_proto;
  '' $scheme;
}

upstream ai_pt_backend {
  server backend:3000;
  keepalive 32;
}

upstream ai_pt_minio {
  server minio:9000;
  keepalive 32;
}

server {
  listen 80 default_server;
  server_name _;

  server_tokens off;

  return 444;
}

server {
  listen 80;
  server_name api.a2t.jongchoi.com;

  server_tokens off;
  client_max_body_size 125m;

  location / {
    proxy_pass http://ai_pt_backend;
    proxy_http_version 1.1;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-Proto $forwarded_proto;

    proxy_connect_timeout 10s;
    proxy_read_timeout 300s;
    proxy_send_timeout 300s;
  }
}

server {
  listen 80;
  server_name s3.a2t.jongchoi.com;

  server_tokens off;
  client_max_body_size 0;

  location / {
    proxy_pass http://ai_pt_minio;
    proxy_http_version 1.1;

    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-Proto $forwarded_proto;
    proxy_set_header Connection '';

    proxy_buffering off;
    proxy_request_buffering off;
    proxy_connect_timeout 10s;
    proxy_read_timeout 300s;
    proxy_send_timeout 300s;
  }
}
